config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "uikit", to: "pages#uikit"

  patch "bookings/:id/cancel", to: "bookings#cancel", as: "cancel_booking"

  resources :rides, except: [:destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: %i[show create] do
      resources :messages, only: %i[create]
    end
    resources :reviews, only: %i[create]
  end

  resources :chatrooms, only: %i[index]
  
  resources :drivers, only: [:show]
  resources :bookings, only: %i[show] do
    resources :reviews, only: [:new, :create]
  end
end

app/views/shared/_header.html.erb
<div class="bg-blue" id='header'>
  <div class="container-fluid d-flex justify-content-between py-2">
    <%= link_to root_path, class: "header-brand" do %>
      <%= image_tag "headerchanges.png" %>
    <% end %>
    <% if user_signed_in? %>
      <p id="Login-name" class='mt-3'><%= current_user.first_name%></p>
      <%#= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "" %>
    <% else %>
      <p class='text-green mt-3'><%= link_to "Login", new_user_session_path, class: "head-link text-decoration-none" %></p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

      <%= link_to root_path do %>
        <%= image_tag 'home.svg' %>
      <% end %>

      <%= link_to chatrooms_path do %>
        <%= image_tag 'message-square.svg' %>
      <% end %>

      <%= link_to root_path do %>
        <%= image_tag 'user.svg' %>
      <% end %>

      <%= link_to dashboard_path do %>
        <%= image_tag 'clipboard.svg' %>
      <% end %>

    <%# Hamburger %>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
  </div>
</div>