config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "uikit", to: "pages#uikit"

  patch "bookings/:id/cancel", to: "bookings#cancel", as: "cancel_booking"

  resources :rides, except: [:destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: %i[show create] do
      resources :messages, only: %i[create]
    end
    resources :reviews, only: %i[create]
  end

  resources :chatrooms, only: %i[index]
  
  resources :drivers, only: [:show]
  resources :bookings, only: %i[show] do
    resources :reviews, only: [:new, :create]
  end
end

app/views/pages/_form.html.erb
<%= simple_form_for :search, url: rides_path, method: :get, html: { class: "home-form" } do |f| %>
  <%= f.input :origin, input_html: { class: "input", placeholder: "Where are you starting from?" }, value: params[:origin], label: false, required: true %>
  <%= f.input :destination, input_html: { class: "input", placeholder: "Where are you going?" }, value: params[:destination], label: false, required: true %>
  <%= f.input :date, input_html: { class: "input", placeholder: "When are you going?", data: { controller: "datepicker" } }, value: params[:date], label: false, required: true %>
  <%= f.input :seats, input_html: { class: "input", placeholder: "How many passengers?"}, value: params[:passengers], label: false %>
  <%= f.button :submit, "Find a ride", class: "btn" %>
<% end %>

app/views/pages/dashboard.html.erb
<%# profile %>
<% if user_signed_in? %>

  <div class="d-flex">
    <div class="profile-picture">
      <%= cl_image_tag current_user.photo.key, class: "avatar-large" %>
    </div>

    <div class="details">
      <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
      <p><%= image_tag 'mail.svg' %>   <%= current_user.email %></p>
      <p><%= image_tag 'phone.svg' %>   <%= current_user.phone_number %></p>
    </div>
  </div>


  <%# Tabs %>
  <ul class="nav nav-pills mb-3 mx-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Request</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Upcoming</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">History</button>
    </li>
  </ul>



  <div class="tab-content" id="pills-tabContent">
    <%# Your request %>
    <div class="tab-pane fade show active" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <% if @bookings.count > 0 %>
        <% @bookings.each do |booking| %>
          <% if booking.status != 'cancelled' && booking.status != 'declined' %>
            <div class="card mx-3 py-3 px-3 d-flex mb-4">
              <div>
                <p><strong><%= booking.ride.driver.user.first_name %></strong></p>
                <p><%= booking.ride.origin %> - <%= booking.ride.destination %></p>
                <p><%= booking.ride.date.strftime("%d.%m") %> * <%= booking.ride.start_time.strftime("%I:%M %p") %></p>
              </div>
              <div class="">
                <%= link_to 'Cancel', cancel_booking_path(booking), class: 'btn btn-primary', data: { "turbo-method": :patch }  %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p class="else-statement px-3">No requests at the moment</p>
      <% end %>
    </div>

    <%# Upcoming rides %>
    <div class="tab-pane fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <%  upcoming_bookings = @bookings.select { |booking| booking.ride.date > Date.today && booking.status == 'confirmed'} %>
      <% if upcoming_bookings.count > 0 %>
        <% upcoming_bookings.each do |booking| %>
          <div class="card mx-3 py-2 mt-4">
            <div id="upcoming-rides" class="px-3">
              <div class="line d-flex">

                <div class="third-image">
                  <%= image_tag "line.svg" %>
                </div>

                <div class="text align-self-center mx-3 my-3">
                  <p><strong><%= booking.ride.origin %></strong></p>
                  <p><%= booking.ride.date.strftime("%d.%m") %> * <%= booking.ride.start_time.strftime("%I:%M %p") %></p>
                  <p><strong><%= booking.ride.destination %></strong></p>
                </div>

              </div>

              <div class="image d-flex mb-3 px-3 py-3">
                <div class="second image">
                  <%= image_tag "icon dashboard.png" %>
                </div>
                <p><%= booking.ride.driver.user.first_name %></p>
              </div>

              <%= booking.ride.remarks %>
            </div>

          </div>
        <% end %>
      <% else %>
        <p class="else-statement px-3">No upcoming rides at the moment</p>
        <% end %>
      <% end %>
    </div>



    <%# Recent rides %>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <%# Check if there are bookings before today %>
      <%  previous_bookings = @bookings.select { |booking| booking.ride.date < Date.today  && booking.status == 'confirmed'} %>

      <% if previous_bookings.count > 0 %>
        <% previous_bookings.each do |booking| %>
            <div class="card mx-3 py-2 mb-4">
              <div id="recent-ride-card" class="px-3">
               <% if booking.ride.driver.photo.present?%>
                <div class="car-image">
                  <%= cl_image_tag booking.ride.driver.photo.key %>
                </div>
              <% else %>
                <div>
                  <%= image_tag "car.png" %>
                </div>
              <% end %>


                <div class="py-2">
                  <p class="mb-3"><strong><%= booking.ride.destination %></strong></p>
                  <p class="mb-1"><%= booking.ride.date.strftime("%d.%m") %> * <%= booking.ride.start_time.strftime("%I:%M %p") %></p>
                </div>
                <div class="">
                  <%= link_to 'Review', new_booking_review_path(booking), class: 'btn btn-primary px-2'  %>
                </div>
              </div>

            </div>
        <% end %>
      <% else %>
        <div class="no-recent-bookings ms-3">
          <p>No recent bookings at the moment</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="logout-button">
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-primary" %>
  </div>

app/views/pages/home.html.erb
<div class="container home-container" id="search-form">
  <h1><strong>Find a ride to your destination</strong></h1>
  <p><strong>Enter your journey details, hop in & go!</strong></p>
  <%= render 'pages/form' %>
</div>
<div class="container home-container benefits">
  <%= image_tag "home.jpg", id: "home-img", alt: "Two people traveling together in a car" %>
  <h2><em>"Wherever you go <br>
      -<br>
      Sync you flow!"</em></h2>
  <h1><strong>Why RoadSync?</strong></h1>
  <div class="benefits-card">
    <h2><strong>Saving costs</strong></h2>
    <%= image_tag "save_money.png", alt: "Two people traveling together in a car" %>
    <h5>Lower Transportation Costs</h5>
    <h5>Reduced Fuel Expenses</h5>
  </div>
  <div class="benefits-card">
    <h2><strong>Environmental Benefits</strong></h2>
    <%= image_tag "environment.png", alt: "Two people traveling together in a car" %>
    <h5>Reduced Carbon Footprint</h5>
    <h5>Decreased Traffic Congestion</h5>
  </div>
  <div class="benefits-card">
    <h2><strong>Social Benefits</strong></h2>
    <%= image_tag "social.png", id: "social-img", alt: "Two people traveling together in a car" %>
    <h5>Getting in touch with new people</h5>
    <h5>Enhanced Safety with a shared ride </h5>
  </div>
  <%= link_to "Find your perfect driver", '#search-form', class: "btn btn-primary mt-3" %>
</div>

app/views/pages/uikit.html.erb
<%# Button %>
<%= link_to 'Go search!', '#', class: 'btn btn-primary'  %>

<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />

<%# index cards %>
<div class="card" id='card-index'>
  <div class="card-info">
    <div>
      <h2>Current location</h2>
      <p>to</p>
      <h2>Destination</h2>
      <%# <p>available on</p> %>
    </div>

    <%# avatar image %>
    <div>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
    </div>
  </div>

  <div class="card-info">
    <p>available</p>
    <p>4€</p>
  </div>
</div>