config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "uikit", to: "pages#uikit"

  patch "bookings/:id/cancel", to: "bookings#cancel", as: "cancel_booking"

  resources :rides, except: [:destroy] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: %i[show create] do
      resources :messages, only: %i[create]
    end
    resources :reviews, only: %i[create]
  end

  resources :chatrooms, only: %i[index]
  
  resources :drivers, only: [:show]
  resources :bookings, only: %i[show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/ride.rb
require_relative "../services/tomtom_service"
class Ride < ApplicationRecord
  belongs_to :driver
  has_many :bookings
  has_many :chatrooms
  has_many :ride_points, dependent: :destroy

  before_save :geocode_endpoints
  after_save :calculate_routes

  private

  def calculate_routes
    tomtom_service = TomtomService.new(ENV.fetch("TOMTOM_API_KEY", nil))

    points = tomtom_service.calculate_route("#{origin_latitude},#{origin_longitude}",
                                            "#{destination_latitude},#{destination_longitude}")

    points.each { |point| RidePoint.create(ride: self, latitude: point["latitude"], longitude: point["longitude"]) }
  end

  def geocode_endpoints
    tomtom_service = TomtomService.new(ENV.fetch("TOMTOM_API_KEY", nil))

    if origin_changed?
      geocoded = tomtom_service.geocode_endpoints(origin_address)

      if geocoded
        self.origin_latitude = geocoded["lat"]
        self.origin_longitude = geocoded["lon"]
      end
    end

    return unless destination_changed?

    geocoded = tomtom_service.geocode_endpoints(destination_address)

    return unless geocoded

    self.destination_latitude = geocoded["lat"]
    self.destination_longitude = geocoded["lon"]
  end
end

app/controllers/rides_controller.rb
require_relative "../services/tomtom_service"

class RidesController < ApplicationController
  before_action :authenticate_user!, only: %i[show]

  def show
    @ride = Ride.find(params[:id])
    @reviews = Review.where(receiver_id: @ride.driver.user_id)
    @chatroom = Chatroom.find_by(ride: @ride, driver: @ride.driver.user, passenger: current_user)
    @chatroom = Chatroom.new if @chatroom.nil?
    @booking = Booking.new
    @map_data = get_map_data(params[:origin], params[:destination])
  end

  def index
    search = params[:search]
    if !params[:search].present? || !search[:origin].present? || !search[:destination].present? || !search[:date].present?
      return render "pages/home", status: :unprocessable_entity
    end

    @origin = search[:origin].downcase

    @destination = search[:destination].downcase
    @date = Date.parse(search[:date])
    @passengers = search[:seats].to_i

    @rides = Ride.joins(:driver).where.not(driver: { user: current_user }).order(:start_time)
    sql_subquery = "DATE(date) = :date #{search[:seats].present? ? 'AND seats >= :passengers' : ''}"

    @rides = @rides.where(sql_subquery, date: @date,
                                        passengers: @passengers).order(:start_time)

    user_points = calculate_route(@origin, @destination)
    return unless user_points.count != 0

    @rides = find_matching_rides(user_points, @rides)
  end

  private

  def calculate_route(origin, destination)
    tomtom_service = TomtomService.new(ENV.fetch("TOMTOM_API_KEY", nil))

    geocodedOrigin = tomtom_service.geocode_endpoints(origin)
    geocodedDestination = tomtom_service.geocode_endpoints(destination)

    tomtom_service.calculate_route("#{geocodedOrigin['lat']},#{geocodedOrigin['lon']}",
                                   "#{geocodedDestination['lat']},#{geocodedDestination['lon']}")
  end

  def find_matching_rides(user_points, rides)
    rides.select do |ride|
      ride_points = ride.ride_points.map { |point| { "latitude" => point.latitude, "longitude" => point.longitude } }
      routes_match?(user_points, ride_points)
    end
  end

  def routes_match?(user_points, driver_points)
    matching_points = user_points & driver_points
    matching_percentage = (matching_points.size.to_f / user_points.size) * 100

    matching_percentage >= 20
  end

  def get_map_data(origin, destination)
    tomtom_service = TomtomService.new(ENV.fetch("TOMTOM_API_KEY", nil))

    geocodedOrigin = tomtom_service.geocode_endpoints(origin)
    geocodedDestination = tomtom_service.geocode_endpoints(destination)

    return {} if geocodedOrigin.nil? || geocodedDestination.nil?

    return { ride: { origin: { city: @ride.origin.capitalize, latitude: @ride.origin_latitude, longitude: @ride.origin_longitude },
                     destination: { city: @ride.destination.capitalize, latitude: @ride.destination_latitude,
                                    longitude: @ride.destination_longitude }, price_per_km: @ride.price_per_km },
             user: { origin: { city: params[:origin].capitalize, latitude: geocodedOrigin["lat"], longitude: geocodedOrigin["lon"] },
                     destination: { city: params[:destination].capitalize, latitude: geocodedDestination["lat"],
                                    longitude: geocodedDestination["lon"] } } }.to_json
  end
end

app/views/rides/_map.html.erb
<div class="map-container"  >
  <div data-map-target="map" style="width: 100%; height: 400px;" id="map"></div>
</div>

app/views/rides/index.html.erb
<div class="container">
  <div class="title-card">
    <div class="title">
      <%= link_to image_tag("arrow-left.svg", alt:"back"), root_path%>
      <h2><%= "Available rides to:" unless @destination.blank?  %></h2>
      <h1><%= @destination %></h1>
      <p><%= "On #{@date.strftime('%d %b %Y')}" unless @date.blank? %></>
    </div>
    <%= image_tag("car-icon.svg", alt:"car", class: "title-img")%>
  </div>

  <div class="container-ride-card">
    <% @rides.each do |ride|%>
      <%= link_to ride_path(ride, origin: @origin, destination:@destination, date:@date, passengers:@passengers), class: "link-ride" do %>
        <div class="card-ride">
          <div class="card-info">
            <%# Line %>
            <div class="third-image">
              <%= image_tag "line.svg" %>
            </div>

            <%# Route %>
            <div class='ride-info'>
              <div class="card-route">
                <h2><%= ride.origin %></h2>
              </div>
              <div class="second-part">
                <h2><%= ride.destination %></h2>
              </div>
            </div>


            <%# Avatar %>
            <div class="avatar-card">
              <%= cl_image_tag ride.driver.user.photo.key, crop: :fill, class:"avatar-bordered" %>
              <p class="avatar-name"><%= ride.driver.user.first_name %></p>
            </div>
          </div>
          <div class="card-available">
            <div class="Price-per-Hour">
              <p><i class="fa-solid fa-euro-sign"></i><%= ride.price_per_km %> /km</p>
            </div>
            <p class="start-time"><i class="fa-regular fa-clock"></i><%= ride.start_time.strftime('%H:%M') %></p>
          </div>
        </div>
      <% end %>
    <%end %>
  </div>

</div>

app/views/rides/show.html.erb
<div class="container show-container" data-controller="map" data-map-key-value="<%= ENV['TOMTOM_API_KEY']%>"
   data-map-map-data-value="<%=@map_data%>" data-map-start-mark-value="<%= asset_path('start-marker.png') %>"
   data-map-end-mark-value="<%= asset_path('end-marker.svg') %>"  data-map-person-start-mark-value="<%= asset_path('person-start-marker.png') %>"
    data-map-person-end-mark-value="<%= asset_path('person-end-marker.png') %>">
  <%= render "map"%>
  <div class="line-ride-card">
    <%= image_tag("line.svg", alt: "journey") %>
    <div class="show-info">
      <div class="line-ride-card-route" id="origin">
        <h1><%= params[:origin].capitalize %></h1>
        <div class="date-time-container">
          <%= image_tag("calendar.svg", alt: "calendar") %>
          <p><%= @ride.date.strftime('%d %b %Y') %></p>
          <p><%= @ride.start_time.strftime('%H:%M') %></p>
        </div>
      </div>
      <div class="line-ride-card-route" id="destination">
        <h1><%= params[:destination].capitalize %></h1>
        <p><span data-map-target="total"> <%= @ride.price_per_km %></span> €</p>
      </div>
    </div>
  </div>
  <div class="show-driver-card">
    <%= cl_image_tag @ride.driver.user.photo.key, crop: :fill, class:"avatar-bordered" %>
    <div class="driver-info">
      <%= link_to driver_path(@ride.driver, ride_id:@ride.id, origin: params[:origin], destination:params[:destination], date:params[:date], passengers:params[:passengers]), class: "text-decoration-none text-darkblue" do %>
        <h2><%= @ride.driver.user.first_name %></h2>
      <% end %>
      <p><%= @ride.driver.car_model %></p>
    </div>
    <% if @chatroom.nil? %>
      <%= link_to ride_chatrooms_path(@ride,origin: params[:origin], destination:params[:destination], date:params[:date], passengers:params[:passengers] ), data: { "turbo-method": :post } do %>
        <%= image_tag('chat.svg', alt: 'Chat with driver') %>
      <% end %>
    <% else %>
      <%= link_to ride_chatroom_path(@ride, @chatroom, origin: params[:origin], destination:params[:destination], date:params[:date], passengers:params[:passengers]) do %>
        <%= image_tag('chat.svg', alt: 'Chat with driver') %>
      <% end %>
    <% end %>
  </div>
  <%= simple_form_for ([@ride, @booking]), html: {class: "ride-book-card"} do |f| %>
    <div class="ride-book-input">
      <%= f.input :seats, input_html: {value: 1}%>
    </div>
    <div class="ride-book-container">
      <%= f.button :submit, "Book" %>
    </div>
  <% end %>
</div>